package com.example.betternutritions.model

data class Nutriments(
    val dummy: Int
    /*
    val carbohydrates: Int,
    val carbohydrates_100g: Int,
    val carbohydrates_unit: String,
    val carbohydrates_value: Int,
    val energy: Int,
    val energy-kcal: Int,
    val energy-kcal_100g: Int,
    val energy-kcal_unit: String,
    val energy-kcal_value: Int,
    val energy-kcal_value_computed: Double,
    val energy_100g: Int,
    val energy_unit: String,
    val energy_value: Int,
    val fat: Int,
    val fat_100g: Int,
    val fat_unit: String,
    val fat_value: Int,
    val fruits-vegetables-nuts-estimate-from-ingredients_100g: Int,
    val fruits-vegetables-nuts-estimate-from-ingredients_serving: Int,
    val nova-group: Int,
    val nova-group_100g: Int,
    val nova-group_serving: Int,
    val nutrition-score-fr: Int,
    val nutrition-score-fr_100g: Int,
    val proteins: Double,
    val proteins_100g: Double,
    val proteins_unit: String,
    val proteins_value: Double,
    val salt: Double,
    val salt_100g: Double,
    val salt_unit: String,
    val salt_value: Double,
    val saturated-fat: Int,
    val saturated-fat_100g: Int,
    val saturated-fat_unit: String,
    val saturated-fat_value: Int,
    val sodium: Double,
    val sodium_100g: Double,
    val sodium_unit: String,
    val sodium_value: Double,
    val sugars: Int,
    val sugars_100g: Int,
    val sugars_unit: String,
    val sugars_value: Int

     */
)