package com.example.betternutritions.model

data class Nutriments(
    val dummy: Double
    /*
    val carbohydrates: Double,
    val carbohydrates_100g: Double,
    val carbohydrates_unit: String,
    val carbohydrates_value: Double,
    val energy: Double,
    val energy-kcal: Double,
    val energy-kcal_100g: Double,
    val energy-kcal_unit: String,
    val energy-kcal_value: Double,
    val energy-kcal_value_computed: Double,
    val energy_100g: Double,
    val energy_unit: String,
    val energy_value: Double,
    val fat: Double,
    val fat_100g: Double,
    val fat_unit: String,
    val fat_value: Double,
    val fruits-vegetables-nuts-estimate-from-ingredients_100g: Double,
    val fruits-vegetables-nuts-estimate-from-ingredients_serving: Double,
    val nova-group: Double,
    val nova-group_100g: Double,
    val nova-group_serving: Double,
    val nutrition-score-fr: Double,
    val nutrition-score-fr_100g: Double,
    val proteins: Double,
    val proteins_100g: Double,
    val proteins_unit: String,
    val proteins_value: Double,
    val salt: Double,
    val salt_100g: Double,
    val salt_unit: String,
    val salt_value: Double,
    val saturated-fat: Double,
    val saturated-fat_100g: Double,
    val saturated-fat_unit: String,
    val saturated-fat_value: Double,
    val sodium: Double,
    val sodium_100g: Double,
    val sodium_unit: String,
    val sodium_value: Double,
    val sugars: Double,
    val sugars_100g: Double,
    val sugars_unit: String,
    val sugars_value: Double

     */
)